### PR TITLE
removed text

### PR DESCRIPTION
**Pull request by ccsouthard**
Subtle copy adjustments.

### CODE REVIEW

**Comment by notslang** [comment]
I think you deleted the branch that this PR was made on.

**Comment by ccsouthard** [comment]
I didn't delete any branches.  The changes that I made are:

   1.  added photos to hero
   2.  added photos to the bottom slideshows
   3.  removed all text related to weekly or biweekly mowing




Sincerest regards,

Charlie Southard

Founder | Animal57.co |

**Comment by notslang** [comment]
The photos are in a separate PR. That's #11.

This is why I say I think the branch is deleted:

**Comment by ccsouthard** [comment]
I simply wanted to remove all text that suggested weekly or biweekly maintenance packages.

**Review by ccsouthard — COMMENTED** [review]
Please Approve

**Comment by ccsouthard** [comment]
This appears to have already been completed. Unless I am mistaken – this is redundant.

**Pull request closed without merging**
