### PR TITLE
Slideshow img

### PR DESCRIPTION
**Pull request by ccsouthard**
Added one image to home slideshow. One custom hardscape image.
pool-hardscape

### CODE REVIEW

**Comment by notslang** [comment]
This branch is identical to https://github.com/slang800/jkniselylandscaping.com/pull/11 and isn't set to merge into master.

**Comment by ccsouthard** [comment]
There is a different image in this PR. I received a notice that stated that
I was seeking to merge.
https://www.dropbox.com/s/b0op8hllmfjt3hm/Screenshot%202018-08-01%2011.39.38.png?dl=0



Sincerest regards,

Charlie Southard

Founder | Animal57.co |

**Comment by ccsouthard** [comment]
"wants to merge into master"

Sincerest regards,

Charlie Southard

Founder | Animal57.co |

**Comment by notslang** [comment]
@ccsouthard that screenshot is from #11, this is #15.

Here's what this one looks like:

**Comment by ccsouthard** [comment]
I clearly screwed it up. So this image needs to be merged directly with the
master and not that branch with slideshow. My apologies.

**Pull request closed without merging**
